---
title: "practice"
output: html_document
date: "2026-03-02"
# 思いついたコードを書くための場所
---

# source()
```{r}
# 前処理用ファイルをソースとする
source("kaminoko_2025_preparation.R")
```


```{r}
df |> 
  filter(full_wtp_right == 1 & !is.na(purist_dummy)) |> 
  pivot_longer(
    cols = starts_with("v9_"),
    names_to = "satis_content",
    values_to = "value"
  ) |> 
  ggplot(aes(x = value, y = satis_content)) + 
  geom_boxplot(na.rm = TRUE) +
  scale_x_continuous(breaks = 1:10) + 
  facet_wrap(~purist_dummy) +
  labs(title = "神の子訪問満足度・purist_dummy別（CVM適切回答者のみ）")
```


```{r}
df |> 
  filter(!is.na(v11_revisit_intention)) |> 
  ggplot(aes(x = v11_revisit_intention)) +
  geom_bar(aes(y = after_stat(prop), group = 1))
```


```{r}
df$v11_revisit_intention |> 
  table()
```


```{r}
df$v5_companions_cnt |> table()
```


```{r}
df$v6_kaminoko_visits |> table()
```


```{r}
df2 <- df |> 
  mutate(
    kaminoko_visit_dummy = ifelse(v6_kaminoko_visits == "はじめて", 1, 0)
  )
```

```{r}
model <- survreg(
  Surv(L, U, type = "interval2") ~  v3_hokkaido  + v9_access_satisfaction + v9_facility_satisfaction + v9_tourist_spot_satisfaction + v9_general_satisfaction +  + purist_dummy + purist_dummy:v9_facility_satisfaction + purist_dummy:v9_tourist_spot_satisfaction,
  data = df2 |> filter(full_wtp_right == 1 & date == "7月20-21日"),
  dist = "gaussian"
)

model |> summary()
```


```{r}
model <- survreg(
  Surv(L, U, type = "interval2") ~  v3_hokkaido + v9_general_satisfaction +kaminoko_visit_dummy,
  data = df2 |> filter(full_wtp_right == 1),
  dist = "gaussian"
)

model |> summary()
```


```{r}
df$v5_companions_cnt |> table()
```


```{r}
df |> filter(date != "7月20-21日") |> 
  select(starts_with("v7"))
```


```{r}
df |> filter(full_wtp_right == 1) |> 
  count(v14_bid1_wtp, v14_bid1, v14_bid2_yes, v14_bid2_no)
```

```{r}
df |> count(wtp_interval)
```


```{r}
df |> count(date)
```



```{r}
df2 <- df |> 
  filter(!is.na(wtp_interval) & date == "7月20-21日")

df2$wtp_interval |> table()

df3 <- df |> 
  filter(date == "7月20-21日")

df3 |> count()


df |> 
  count(date, yes_no_pattern) |> 
  pivot_wider(names_from = yes_no_pattern, values_from = n)
```


```{r}
library(tidyverse)
y <- c(0, -1, 1, 0, 2, -2, 1, 1, -2)
x <- c(-1, 1, 0, 0, -2, 2, -2, 2, 0)

df_practice <- data.frame(
  y = y,
  x = x
)

model <- lm(y ~ x, data =df_practice)
model |> summary()
```


```{r}
df$v12_interact_by_market |> 
  table()
```


```{r}
df$v11_revisit_intention |> 
  table()
```


```{r}
df |> 
  filter(!is.na(v2_gen)) |> 
  select(v2_gen) |> 
  table()
```

```{r}
df |> 
  filter(!is.na(v6_kaminoko_visits)) |> 
  mutate(
    kaminoko_dummy = case_when(
      v6_kaminoko_visits == "はじめて" ~ "はじめて",
      v6_kaminoko_visits == "2回目" | v6_kaminoko_visits == " 3回目以上" ~ "2回目以上",
      TRUE ~ v6_kaminoko_visits
    )
  ) |> select(kaminoko_dummy)
```

